/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_ddnet_jni_Java2Cpp */

#ifndef _Included_top_ddnet_jni_Java2Cpp
#define _Included_top_ddnet_jni_Java2Cpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_ddnet_jni_Java2Cpp
 * Method:    dllAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_top_ddnet_jni_Java2Cpp_dllAdd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     top_ddnet_jni_Java2Cpp
 * Method:    dllSub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_top_ddnet_jni_Java2Cpp_dllSub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     top_ddnet_jni_Java2Cpp
 * Method:    dllMul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_top_ddnet_jni_Java2Cpp_dllMul
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     top_ddnet_jni_Java2Cpp
 * Method:    dllDiv
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_top_ddnet_jni_Java2Cpp_dllDiv
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
